import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import { ContentContainer } from "../../components/common/ContentContainer";
import { ContentContainerTitle } from "../../components/common/ContentContainerTitle";
import { MainContainer } from "../../components/common/MainContainer";
import { Navigation } from "../../components/common/Navigation";
import { trpc } from "../../utils/trpc";

const UserPage: NextPage = () => {
  const router = useRouter();
  const userQuery = trpc.players.getUser.useQuery({
    userId: parseInt(
      typeof router.query.id === "string" ? router.query.id : "0"
    ),
  });

  return (
    <>
      <Head>
        <title>Elite Bronze - {userQuery.data?.login}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Navigation />

        <ContentContainer>
          <ContentContainerTitle text={userQuery.data?.login ?? ""} />
        </ContentContainer>
      </MainContainer>
    </>
  );
};

export default UserPage;
