import type { NextPage } from "next";
import Head from "next/head";
import { Navigation } from "../../components/common/Navigation";


const UsersIndex: NextPage = () => {
  const users = Array.from({ length: 56 }).map((_, index) => ({ userId: index + 1, name: `User ${index + 1}`}))

  return (
    <>
      <Head>
        <title>Elite Bronze - Turnieje</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-neutral-900 h-full w-full flex pr-8">
        <Navigation />

        <section className="w-11/12 h-full py-6">
          <div className="bg-zinc-800 shadow-2xl h-full rounded-xl">
            <div className="w-full h-full flex flex-wrap gap-12 overflow-y-auto p-8 items-center justify-center">
              {users.map((user) => {
                return (
                  <div key={`user-index-${user.userId}`} className="w-24 relative h-24 border-2 border-violet-900 bg-zinc-800 rounded-md cursor-pointer transition-all hover:border-violet-700 hover:border-8" title={user.name}>
                    <div className="absolute -bottom-8 w-full text-center text-zinc-50 overflow-hidden whitespace-nowrap text-ellipsis">{user.name}</div>
                  </div>
                )
              })}
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default UsersIndex;
