import type { NextPage } from "next";
import Head from "next/head";
import { Navigation } from "../../components/common/Navigation";

const TournamentIndex: NextPage = () => {
  const tournaments = Array.from({ length: 5 }).map((_, index) => ({ tournamentId: index + 1, name: `Elite Bronze ${index + 1}`}))

  return (
    <>
      <Head>
        <title>Elite Bronze - Turnieje</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-neutral-900 h-full w-full flex pr-8">
        <Navigation />

        <section className="w-11/12 h-full py-6">
          <div className="bg-zinc-800 shadow-2xl h-full rounded-xl">
            <div className="w-full h-full flex gap-16 overflow-y-auto items-center px-16">

            {tournaments.map((tournament) => {
              return (
                <div key={`tournament-index-${tournament.tournamentId}`}>
                  <div className="w-96 h-96 rounded-lg bg-zinc-900 border-4 border-violet-900 flex flex-col relative">
                    <div className="absolute right-0 border-l-4 border-b-4 px-8 rounded-bl-xl border-violet-900 bg-violet-900">
                      <span className="text-zinc-50">Zakończony</span>
                    </div>

                    <picture className="flex-1">
                      <img className="h-full object-contain px-2" src="/ebIlogo.png" alt="Elite Bronze I Logo" />
                    </picture>

                    <div className="flex flex-1 flex-col">
                      <div className="w-full text-center border-t-4 border-b-4 py-2 border-violet-900 bg-violet-900">
                        <span className="text-slate-300 text-3xl">
                          {tournament.name}
                        </span>
                      </div>

                      <div className="flex flex-1 text-zinc-50 px-4">
                        <div className="flex-1 flex flex-col justify-center gap-2">
                          <div><span className="">🏆</span> iiri</div>
                          <div><span className="">🏆</span> iRaD</div>
                          <div><span className="">🏆</span> TimeWinner</div>
                        </div>

                        <div className="w-20 flex flex-col justify-center gap-2">
                          <div className="border-2 border-violet-900 rounded-xl p-1 grid place-items-center">G: 12</div>
                          <div className="border-2 border-violet-900 rounded-xl p-1 grid place-items-center">M: 26</div>
                        </div>
                      </div>
                    </div>
                    </div>
                </div>
              )
            })}
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default TournamentIndex;
